### ISSUE TITLE
Why is data represented as `[u16; 3]`?

### ISSUE THREAD

**Issue by vrtgs** [Chubercik/i48#1]
We're going backwards, it's clunky, it's odd and it feels like it serves zero purpose, and it's harder to reason with than `[u8; 6]`.

**Comment by Chubercik** [comment]
![you_got_me](https://github.com/user-attachments/assets/3124c4d4-ec51-4394-b25e-08116e65f5b2)

TBH the choice was pretty arbitrary, `u16` is the largest native type, which multiple of would give you 48 bits (another option would be `u32` + `u16`, but that wouldn't go into a `Vec` without an `enum`).

For now, I'm going to do what [`intx`](https://crates.io/crates/intx) does and rewrite `i48` to use `[u8; 6]`, this of course being subject to change in the future, if a better option comes up.

**Comment by vrtgs** [comment]
> this of course being subject to change in the future, if a better option comes up.

I mean u can go take a look at [what I did at i24](https://github.com/jmg049/i24/pull/5)
